const animes = [
  { 
    name: "Spy x Family", 
    file: "Spy.html", 
    poster: "https://wallpapercg.com/media/ts_orig/12773.webp", 
    alt: "Spy x Family Poster",
    genre: "Action • Comedy", 
    episodes: "▶️ 37",
    studio: "WIT Studio, CloverWorks",
    rating: "⭐ 5", 
    description: "In order to maintain a fragile peace between East and West, master spy Twilight must infiltrate an elite private school. To do so, he creates a fake family with an assassin wife and a telepathic daughter who secretly know each other's hidden lives.",
    hook: "A master spy, a deadly assassin, and a telepathic child play house to save the world.",
    quote: "For the sake of the mission, and for a better world where children don't have to cry.",
    watch: "https://aniwatchtv.to/watch/spy-x-family-17977?ep=89506",
    trailer: "https://www.youtube.com/embed/JP6vBnazpWI?si=OH9rmN6oZcCbbUVU",
    laugh: "https://www.youtube.com/watch?v=-QOPZSAUn7s",
    spotify: "https://open.spotify.com/embed/album/7e4jxoNaSmYXIWq7qQfQ0r?utm_source=generator",
    keyGenre: "Action, Comedy, Shonen, Slice of Life, Spy, Espionage, Family Dynamics, Found Family, Secret Identity, Parenting, School Life, Undercover, Tactical, Historical Fiction, Thriller, Satire, Wholesome, Life Lessons",
    keywords: "Espionage, assassin, telepath, forger, secrets, mission, family, wholesome, comedy, operation, academy, peace, disguise.",
    trending: false,
    best: false,
    gold: true, silver: false, bronze: false
  },
  { 
    name: "Frieren: Beyond Journey's End",
    file: "Frieren.html", 
    poster: "https://media.printler.com/media/photo/185948.jpg?rmode=crop&width=638&height=900", 
    alt: "Frieren Poster",
    genre: "Adventure • Fantasy", 
    episodes: "▶️ 28",
    studio: "Madhouse",
    rating: "⭐ 5", 
    description: "Decades after the Hero's party defeated the Demon King, the immortal elf mage Frieren watches her comrades pass away. Realizing how fleeting human life is, she embarks on a new quest to the land of souls to say the words she never got to speak.",
    hook: "An immortal elf mage learns the value of human connection long after the quest is over.",
    quote: "I realized I knew nothing about the humans I traveled with.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Adventure, Fantasy, Shonen, Seinen, Slice of Life, Philosophical, High Fantasy, Life Lessons, Journey, Magic System, Melancholy, Atmospheric, Nostalgia, Coming of Age, Historical, Legacy, Peace, Quiet Growth",
    keywords: "Elf, mage, immortality, legacy, journey, time, friendship, party, hero, demons, magic, melancholy.",
    trending: false,
    best: false, 
    gold: false, silver: false, bronze: false
  },
  { 
    name: "Solo Leveling",
    file: "Solo.html", 
    poster: "https://i.pinimg.com/736x/68/f9/81/68f98176832dd0d1b365ef6bd883d494.jpg", 
    alt: "Solo Leveling Poster",
    genre: "Action • Fantasy", 
    episodes: "▶️ 12",
    studio: "A-1 Pictures",
    rating: "⭐ 5", 
    description: "In a world where hunters clear dungeons to protect humanity, Sung Jin-woo is the weakest of them all. After a near-death experience in a double dungeon, he is chosen by a mysterious 'System' that allows him to level up without limits, turning him into a god-like Shadow Monarch.",
    hook: "The world's weakest hunter survives a hidden trial to become the ultimate player.",
    quote: "The System used me, and now I will use the System. Arise.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Action, Fantasy, Shonen, Overpowered, Leveling, RPG Mechanics, Dungeon Crawl, Progression Fantasy, Survival, Urban Fantasy, Dark Fantasy, Zero to Hero, Necromancy, Monster Hunter, Thriller, Supernatural, Martial Arts",
    keywords: "Hunter, dungeons, leveling, system, shadows, monarch, power, growth, gates, monsters, raids, necromancy.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "The Reincarnation of the Strongest Exorcist in Another World", 
    file: "Exorcist.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BNDZjNTgyNDktZTJmZi00YzQ3LWJjNGMtOWQ0ODE1OGMwNmMzXkEyXkFqcGc@._V1_.jpg", 
    alt: "Strongest Exorcist Poster",
    genre: "Fantasy • Isekai", 
    episodes: "▶️ 13",
    studio: "Studio Blanc",
    rating: "⭐ 4", 
    description: "After being betrayed by his own disciples, the world's strongest exorcist uses a secret reincarnation spell. Reborn into a world of magic where he lacks any mana, he realizes his ancient yin-yang arts are far superior to the local sorcery.",
    hook: "A betrayed master of spirits is reborn in a world of magic where he lacks mana but rules the occult.",
    quote: "I don't need magic. These 'insignificant' arts from my previous life are more than enough to crush you.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Fantasy, Action, Shonen, Reincarnation, Supernatural, Overpowered, School Life, Magic System, Strategy, Occult, Exorcism, Mythology, Tactical, Betrayal, Noble Society, Spirits, Academy, Revenge",
    keywords: "Exorcist, reincarnation, magic, spirits, betrayal, overpowered, isekai, cunning, strategy, talismans.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "Mushoku Tensei: Jobless Reincarnation",
    file: "Tensei.html", 
    poster: "https://a.storyblok.com/f/178900/1920x1080/22d162c483/mushoku-tensei-jobless-reincarnation.png/m/1200x0/filters:quality(95)format(webp)", 
    alt: "Mushoku Tensei Poster",
    genre: "Adventure • Drama", 
    episodes: "▶️ 48",
    studio: "Studio Bind",
    rating: "⭐ 5", 
    description: "A 34-year-old shut-in dies and is reborn as Rudeus Greyrat. Keeping his adult memories, he resolves to live this life to the fullest, mastering magic from childhood and navigating a massive world full of danger, political shifts, and personal growth.",
    hook: "A shut-in gets a second chance at life in a world of magic, vowing to live without regrets.",
    quote: "In this world, I will give it my all. I will live my life so that I have no regrets when I die again.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Adventure, Fantasy, Seinen, Drama, Reincarnation, Coming of Age, World Building, Magic System, High Fantasy, Life Lessons, Redemption, Philosophical, Journey, Romance, Survival, Tragedy, Lore, Harem",
    keywords: "Isekai, redemption, magic, life, growth, family, tragedy, world-building, journey, wizard, reincarnation.",
    trending: false,
    best: true,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "Mashle: Magic and Muscles",
    file: "Mash.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BMTUwMjM2ZTctMjI5Yi00MjIwLWJlYzAtNjk5MDQ0NTlmZWJjXkEyXkFqcGc@._V1_.jpg", 
    alt: "Mashle Poster",
    genre: "Comedy • Fantasy", 
    episodes: "▶️ 24",
    studio: "A-1 Pictures",
    rating: "⭐ 5", 
    description: "In a world where magic status determines social standing, Mash Burnedead is born without a single drop of mana. To protect his peaceful life with his father, he enrolls in Easton Magic Academy, using his sheer physical strength to shatter spells and logic alike.",
    hook: "In a world where magic is everything, one boy uses raw physical power to crush the elite.",
    quote: "If I can't use magic, I'll just have to crush your spells with my bare hands.",
    watch: "https://aniwatchtv.to/watch/mashle-magic-and-muscles-18339?ep=100069",
    trailer: "https://www.youtube.com/embed/_ce5_P1Hj5A?si=DuLSeLJuKKPBDsoD",
    laugh: "https://www.youtube.com/watch?v=9pdVpqPyFu8",
    spotify: "https://open.spotify.com/embed/playlist/6YO8wCQJBISVRivbCnbMMq?utm_source=generator",
    keyGenre: "Comedy, Fantasy, Action, Shonen, Parody, Satire, Gag, Slapstick, Underdog, Overpowered, School Life, Magic Academy, Martial Arts, Fitness, Supernatural, Battle, Social Satire, Absurdist Humor",
    keywords: "Muscles, magic, school, comedy, parody, cream-puffs, strength, weights, wizardry, satire, academy.",
    trending: false,
    best: true,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "The Aristocrat's Otherworldly Adventure", 
    file: "Aristocrat.html", 
    poster: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=cover,format=auto,quality=85,width=1920/keyart/GVDHX8QK5-backdrop_wide", 
    alt: "Aristocrat's Adventure Poster",
    genre: "Action • Fantasy", 
    episodes: "▶️ 12",
    studio: "EMT Squared, Magic Bus",
    rating: "⭐ 3", 
    description: "Cain von Silford is reborn as a noble with the blessings of seven gods who took their gifts a bit too far. Now possessing god-tier stats, he must hide his overwhelming power to live a normal school life while inadvertently becoming the kingdom's secret weapon.",
    hook: "Reborn with the excessive blessings of seven gods, a young noble tries to hide his world-breaking power.",
    quote: "The gods were a little too generous... How am I supposed to live a normal life with these stats?",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Fantasy, Action, Shonen, Reincarnation, Overpowered, Noble Society, Kingdom Building, High Society, School Life, Magic System, Adventure, Harem, Leveling, Divine Blessing, Comedy, Slice of Life",
    keywords: "Noble, god-blessed, overpowered, isekai, reincarnation, child-prodigy, magic, status, leveling, fantasy.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "The Misfit of Demon King Academy", 
    file: "Misfit.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BY2MzZGVhZTgtNWZlYi00NGI5LTk5N2QtYTkzMzNkMWM0NjBhXkEyXkFqcGc@._V1_.jpg", 
    alt: "Misfit of Demon King Academy Poster",
    genre: "Fantasy • School", 
    episodes: "▶️ 37",
    studio: "SILVER LINK.",
    rating: "⭐ 4", 
    description: "Anos Voldigoad, the Demon King of Tyranny, sacrificed his life to end a war 2,000 years ago. Reincarnated into a modern era of peace, he finds that his descendants have become weak and the history of his very existence has been rewritten to favor an impostor.",
    hook: "The legendary Demon King reincarnates after 2,000 years only to find his legacy has been erased.",
    quote: "Did you think that killing me would be enough to make me die?",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Fantasy, Action, Shonen, Overpowered, School Life, Reincarnation, Demon Lord, Supernatural, Magic System, Academy, Mythology, Battle, High Society, Legend, Historical Fantasy, Comedy, Arrogant Protagonist",
    keywords: "Demon-king, reincarnation, academy, overpowered, lineage, magic, arrogance, school, battle, legacy.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "The Greatest Demon Lord Is Reborn as a Typical Nobody", 
    file: "DLord.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BZTE0ZmQ0ZmYtYjllZS00MDg0LTk3YzMtYzBhMDk4ZjUzNzAyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Greatest Demon Lord Poster",
    genre: "Fantasy • Magic", 
    episodes: "▶️ 12",
    studio: "SILVER LINK., BLADE",
    rating: "⭐ 3", 
    description: "Varvatos was the most powerful being in history, but his power left him lonely and isolated. Deciding to reincarnate as a 'typical nobody' named Ard, he finds that the world's overall magic level has dropped so much that even his 'average' efforts make him a legend.",
    hook: "A lonely Demon Lord seeks a normal life by reincarnating as a commoner, but he's still too powerful.",
    quote: "I just wanted to make friends. I didn't think I'd still be this much stronger than everyone else.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Fantasy, Magic, Action, Shonen, Reincarnation, Overpowered, School Life, Demon Lord, Comedy, Harem, Supernatural, Academy, Battle, Past Life, Coming of Age, Secret Identity, Friendship",
    keywords: "Demon-lord, reincarnation, nobody, school, magic, loneliness, friendship, overpowered, academy.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "Re: Zero - Starting Life in Another World",
    file: "ReZero.html", 
    poster: "https://preview.redd.it/re-zero-starting-life-in-another-world-season-4-new-key-v0-0wi3zxkael1g1.jpeg?auto=webp&s=77d1fe2aedb47b9d6414b19d928f4e657f16d863", 
    alt: "Re: Zero Poster",
    genre: "Drama • Psychological", 
    episodes: "▶️ 58",
    studio: "White Fox",
    rating: "⭐ 3", 
    description: "Subaru Natsuki is suddenly summoned to a fantasy world with no special powers—except for 'Return by Death.' This ability forces him to relive traumatic events repeatedly until he can find a way to prevent the deaths of his new friends and the girl he loves.",
    hook: "A powerless boy must die repeatedly to rewrite a tragic destiny in a cruel fantasy world.",
    quote: "I will save you. No matter how many times I have to die to do it.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Psychological, Drama, Fantasy, Seinen, Thriller, Survival, Dark Fantasy, Time Loop, Tragedy, Mystery, Supernatural, Gore, Resilience, Life Lessons, Magical Realism, Romance, Horror",
    keywords: "Loop, death, suffering, psychological, isekai, return-by-death, magic, witches, cult, pain.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "I Was Reincarnated As The 7th Prince", 
    file: "7thPrince.html", 
    poster: "https://a.storyblok.com/f/178900/1200x675/299dac8631/i-was-reincarnated-as-the-7th-prince-staffel-2.jpg/m/1200x0/filters:quality(95)format(webp)", 
    alt: "7th Prince Poster",
    genre: "Fantasy • Magic", 
    episodes: "▶️ 12",
    studio: "Tsumugi Akita Animation",
    rating: "⭐ 5", 
    description: "A commoner mage who died wishing he could have studied magic more is reborn as Lloyd, the 7th prince of the Saloum Kingdom. Now a child prodigy with vast resources and zero responsibilities, he uses his royal status to conduct dangerous and forbidden magic research.",
    hook: "A magic-obsessed mage is reborn as a prince and uses his royal status to master forbidden sorcery.",
    quote: "I want to see more magic. There's so much I couldn't reach in my last life.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Fantasy, Magic, Isekai, Shonen, Overpowered, Reincarnation, Research, Scientific Magic, Adventure, Action, Comedy, Royal Society, High Society, Sorcery, Battle, Child Protagonist, Exploration",
    keywords: "Prince, magic-nerd, reincarnation, research, sorcery, spells, overpowered, obsession, experiment.",
    trending: false,
    best: true,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "The Apothecary Diaries",
    file: "Apothecary.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BNjAxMmFjZjgtYjM1ZS00NzdmLTliZDktZmIyMzU5YTBlNDBmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Apothecary Diaries Poster",
    genre: "Drama • Mystery", 
    episodes: "▶️ 24",
    studio: "TOHO animation STUDIO",
    rating: "⭐ 5", 
    description: "Maomao, a young woman raised in the red-light district, is kidnapped and sold to the imperial palace as a lowly servant. Her knowledge of poisons and medicine eventually catches the eye of an influential eunuch, leading her to solve intricate mysteries within the Inner Court.",
    hook: "An eccentric herbalist uses her knowledge of poisons to solve deadly mysteries within the Emperor's palace.",
    quote: "It's a matter of dosage. Anything can be a medicine or a poison depending on how you use it.",
    watch: "https://aniwatchtv.to/watch/the-apothecary-diaries-18578?ep=108898",
    trailer: "https://www.youtube.com/embed/XYNGkSvFT8c?si=VuALbWtpMFzPMfmL",
    laugh: "https://www.youtube.com/watch?v=1GgX5_DTaGI",
    spotify: "https://open.spotify.com/embed/album/60GhreuWPvQvllHiuvptsJ?utm_source=generator",
    keyGenre: "Mystery, Drama, Historical, Seinen, Shoujo, Medical, Forensics, Detective, Analytical, Political Intrigue, High Society, Court Drama, Slice of Life, Science, Psychological, Romance, Life Lessons",
    keywords: "Apothecary, poison, palace, mystery, medicine, court-intrigue, herbalist, detective, concubines.",
    trending: false,
    best: true,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "The Hero Is Overpowered but Overly Cautious", 
    file: "Cautious.html", 
    poster: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=cover,format=auto,quality=85,width=1920/keyart/GNVHKN78X-backdrop_wide", 
    alt: "Overly Cautious Hero Poster",
    genre: "Comedy • Fantasy", 
    episodes: "▶️ 12",
    studio: "White Fox",
    rating: "⭐ 4", 
    description: "The goddess Ristarte summons a hero named Seiya to save a high-difficulty world. While his stats are incredible, Seiya is absurdly cautious, refusing to leave his room until he has hundreds of spare items and is a much higher level than the bosses he needs to fight.",
    hook: "A hero with god-tier stats refuses to fight until he is 1000% prepared for every possible scenario.",
    quote: "Ready perfectly. I won't move an inch until I'm absolutely certain of victory.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Comedy, Fantasy, Isekai, Shonen, Overpowered, Parody, Satire, Strategy, Tactical, Adventure, Survival, RPG Mechanics, Slapstick, Training, Dark Comedy, Supernatural, Magic System",
    keywords: "Caution, hero, training, preparation, comedy, goddess, isekai, stats, monsters, overkill.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "The Water Magician", 
    file: "WaterMagician.html", 
    poster: "https://i.tribune.com.pk/media/images/water-magician1758283363-0/water-magician1758283363-0-412x290.webp", 
    alt: "Water Magician Poster",
    genre: "Fantasy • Slice of Life", 
    episodes: "▶️ 12",
    studio: "Seven Arcs",
    rating: "⭐ 5", 
    description: "In a world where magic is often used for war, a gentle young man discovers he has a unique affinity for water magic. Rather than seeking glory, he uses his powers to help his rural village thrive, proving that the most powerful magic is that which sustains life.",
    hook: "A gentle mage uses his rare affinity for water to build a peaceful life instead of going to war.",
    quote: "Water can heal anything. It’s the source of all life and the calmest magic there is.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Fantasy, Slice of Life, Seinen, Relaxing, Iyashikei, Atmospheric, Nature, Peaceful, Magic System, Creative, Simple Life, Community, Farming, Gentle, Life Lessons, Meditation, Rural",
    keywords: "Water, magic, relaxing, slice-of-life, fantasy, village, nature, calm, adventure, elements.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "The Eminence In Shadow",
    file: "Eminence.html", 
    poster: "https://media.animationdigitalnetwork.com/images/show/d0465ad8-4974-4331-bc12-3a8a3a02cb77/affiche.width=630,height=900,quality=80", 
    alt: "Eminence In Shadow Poster",
    genre: "Action • Comedy", 
    episodes: "▶️ 32",
    studio: "Nexus",
    rating: "⭐ 5", 
    description: "Cid Kagenou is obsessed with being a 'mastermind in the shadows.' Reincarnated in a magic world, he creates a fake backstory about an evil cult to play out his roleplay fantasies—only to find out that the cult is completely real and he's accidentally leading a global resistance.",
    hook: "A boy obsessed with mastermind tropes accidentally creates a real secret organization and fights a real cult.",
    quote: "I am... Atomic. In the shadows, I lurk and hunt the shadows.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Action, Comedy, Isekai, Shonen, Overpowered, Parody, Satire, Chuunibyou, Secret Identity, Dark Fantasy, Psychological, Mystery, Secret Society, Martial Arts, Harem, Tactical, Roleplay, Magic System",
    keywords: "Chuunibyou, shadow, garden, organization, mastermind, comedy, parody, overpowered, isekai.",
    trending: false,
    best: true,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "Villainess Level 99: I May Be the Hidden Boss But I'm Not the Demon Lord", 
    file: "Level99.html", 
    poster: "https://m.media-amazon.com/images/I/81VKA-DwQzL._UF1000,1000_QL80_.jpg", 
    alt: "Villainess Level 99 Poster",
    genre: "Fantasy • Villainess", 
    episodes: "▶️ 12",
    studio: "Jumondou",
    rating: "⭐ 4", 
    description: "Reborn as Eumiella Dolkness, the hidden boss of an otome game, a girl spends her childhood grinding levels to avoid being killed. By the time she reaches the academy, she is already Level 99, leading everyone to mistakenly believe she is the new Demon Lord.",
    hook: "A gamer reborn as a villainess hits max level to avoid her fate, only to be mistaken for the Demon Lord.",
    quote: "I just like to grind. I didn't mean to become more powerful than the actual demon lord.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Fantasy, Villainess, Shoujo, Overpowered, Leveling, RPG Mechanics, School Life, Comedy, Magic System, Dark Magic, Social Satire, Reincarnation, Noble Society, Adventure, Strategy",
    keywords: "Villainess, leveling, dark-magic, boss, game, stats, academy, misunderstanding, overpowered.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "I'm in Love with the Villainess", 
    file: "YuriVillainess.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BMGMzMjNkYzYtNWZlMS00MDI3LTk1NjMtZDljZmE5OWRhNzMxXkEyXkFqcGc@._V1_.jpg", 
    alt: "In Love with the Villainess Poster",
    genre: "Comedy • Romance", 
    episodes: "▶️ 12",
    studio: "Platinum Vision",
    rating: "⭐ 4", 
    description: "Rei Ohashi finds herself inside her favorite otome game, but instead of the handsome princes, she is hopelessly in love with the game's cruel villainess, Claire François. Rei uses her knowledge of the game to win Claire's heart while navigating the game's dark political undertones.",
    hook: "A girl reincarnates into a game and skips the princes to pursue the arrogant villainess instead.",
    quote: "I love you, Miss Claire! I'll stay by your side even if the whole world turns against you.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Yuri, Romance, Comedy, Shoujo, Villainess, Otome, School Life, Social Satire, Political Intrigue, High Society, Slice of Life, LGBTQ+, Parody, Magic System, Reincarnation, Drama",
    keywords: "Villainess, yuri, romance, otome-game, isekai, devotion, comedy, obsession, school, noble.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "7th Time Loop", 
    file: "7thLoop.html", 
    poster: "https://m.media-amazon.com/images/I/91sHdmMFw6L._UF1000,1000_QL80_.jpg", 
    alt: "7th Time Loop Poster",
    genre: "Romance • Fantasy", 
    episodes: "▶️ 12",
    studio: "Studio Kai, HORNETS",
    rating: "⭐ 5", 
    description: "Rishe has already lived six lives, each ending in her death at age 20. In each loop, she mastered a different profession, from merchant to knight. In her seventh life, she is proposed to by the very prince who killed her in a previous loop, and she must use all her skills to change their fate.",
    hook: "A woman uses skills from six past lives to survive being married to the prince who killed her.",
    quote: "I will live a long life this time. I’ll use every skill I’ve learned to ensure it.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Romance, Fantasy, Shoujo, Drama, Historical, Time Loop, Reincarnation, Political Intrigue, Strategy, Noble Society, High Society, Survival, Medical, Business, Martial Arts, Mystery, Life Lessons",
    keywords: "Loop, reincarnation, noble, survival, skills, time, destiny, romance, marriage, prince, villain.",
    trending: false,
    best: true,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "I'll Become A Villainess Who Goes Down In History", 
    file: "VillainessHistory.html", 
    poster: "https://fr.web.img2.acsta.net/img/61/27/612765b791b31b8fdf0d317486ed731b.jpg", 
    alt: "Villainess History Poster",
    genre: "Fantasy • Drama", 
    episodes: "▶️ 13",
    studio: "MAHO FILM",
    rating: "⭐ 5", 
    description: "Alicia hates typical goody-two-shoes heroines, so when she is reincarnated as her favorite otome game villainess, she vows to be the greatest villain in history. To do this, she trains harder than anyone in magic and swordsmanship, inadvertently winning everyone's respect.",
    hook: "A girl tries her hardest to be a legendary villain, only to accidentally become a beloved prodigy.",
    quote: "I'll be the greatest villain. If I’m going to be bad, I might as well be the best at it.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Villainess, Fantasy, Drama, Shoujo, Reincarnation, Strategy, Noble Society, High Society, Political Intrigue, Social Reform, Training, Magic System, Psychological, Ambition, Historical Fantasy",
    keywords: "Villainess, evil, ambition, reincarnation, history, legacy, noble, child, training, magic.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "I May Be A Guild Receptionist But I'll Solo To Clock Out on Time", 
    file: "Receptionist.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BMzA3N2U1NDQtYzQyZi00NmY2LWEzZjktMTU2OWFiZWViNzZlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Guild Receptionist Poster",
    genre: "Action • Comedy", 
    episodes: "▶️ 12",
    studio: "CloverWorks",
    rating: "⭐ 4", 
    description: "Alina just wants a steady desk job so she can leave work at 5 PM. However, when the guild's incompetent adventurers fail to clear dungeons, her workload increases. To solve the problem, she secretly enters the dungeons herself and obliterates bosses in record time.",
    hook: "A tired office worker secretly hunts high-level bosses just so she can finish her paperwork by 5 PM.",
    quote: "I'm leaving at five. If the boss is in the way, I'll just have to crush it myself.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Action, Comedy, Fantasy, Seinen, Overpowered, Satire, Workplace Drama, Slice of Life, Monster Hunter, Dungeon Crawl, Parody, Corporate Satire, Magic System, Secret Identity, Daily Life",
    keywords: "Receptionist, guild, desk-job, overtime, combat, overpowered, secret-strength, monster, hunting.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "KonoSuba", 
    file: "KonoSuba.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BNTQ5NzJjMjgtNDliNC00YTdmLWJiOTQtYWRiMzY4OWU5NGQ3XkEyXkFqcGc@._V1_.jpg", 
    alt: "KonoSuba Poster",
    genre: "Comedy • Adventure", 
    episodes: "▶️ 31",
    studio: "Studio Deen / Drive",
    rating: "⭐ 4", 
    description: "Kazuma Satou dies an embarrassing death and is offered a chance to reincarnate in a fantasy world. He chooses to bring the goddess Aqua with him as his 'special item,' only to realize she's useless. Together with a masochistic knight and a one-shot mage, they form the world's most dysfunctional party.",
    hook: "A boy is reincarnated into a world of adventure with a useless goddess and a team of idiots.",
    quote: "Explosion! My life for one single, perfect explosion a day!",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Comedy, Isekai, Adventure, Fantasy, Shonen, Parody, Satire, Slapstick, RPG Mechanics, Magic System, Reincarnation, Supernatural, Absurdist Humor, Slice of Life, Quest, Dysfunctional Family",
    keywords: "Comedy, parody, isekai, useless-goddess, explosion-magic, masochist, knight, shut-in, adventure.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "The World Finest Assassin", 
    file: "Assassin.html", 
    poster: "https://m.media-amazon.com/images/I/817IwMgf87L._UF1000,1000_QL80_.jpg", 
    alt: "Finest Assassin Poster",
    genre: "Action • Isekai", 
    episodes: "▶️ 12",
    studio: "SILVER LINK., Studio Palette",
    rating: "⭐ 5", 
    description: "The world's greatest assassin is murdered by the organization he served and is reborn into a world of magic. A goddess tasks him with one final mission: kill the world's 'Hero' before he destroys the planet, using his modern tactical knowledge and new magical gifts.",
    hook: "A modern-day hitman is reborn as a magical noble to carry out one final hit: killing the world's Hero.",
    quote: "Target acquired. In this life, I’ll kill a hero with the skills of an assassin and the knowledge of a mage.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Action, Thriller, Seinen, Assassin, Strategy, Reincarnation, Tactical, Overpowered, Noble Society, High Society, Magic System, Martial Arts, Drama, Adventure, Romance, Mission-based",
    keywords: "Assassin, hitman, reincarnation, tactical, calculation, skills, weapons, magic, noble, mission.",
    trending: false,
    best: true,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "Possibly The Greatest Alchemist Of All Time", 
    file: "Alchemist.html", 
    poster: "https://fr.web.img3.acsta.net/img/b6/74/b674af60032e00a9a2a7e0e233c07613.jpg", 
    alt: "Greatest Alchemist Poster",
    genre: "Fantasy • Adventure", 
    episodes: "▶️ 12",
    studio: "Studio Comet",
    rating: "⭐ 5", 
    description: "After being summoned to another world, a man discovers his only skill is a seemingly useless 'Alchemy.' He soon realizes that his level of crafting is god-tier, allowing him to create items that defy common sense, eventually building a kingdom and changing the global economy.",
    hook: "A man with a 'useless' alchemy skill discovers he can craft items that break the world's laws.",
    quote: "I can make anything. If I need it, I'll just synthesize it from scratch.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Fantasy, Adventure, Shonen, Overpowered, Crafting, Alchemy, Slice of Life, world Building, Economy, Magic System, Trading, Relaxing, Research, Journey, RPG Mechanics, Discovery",
    keywords: "Alchemy, crafting, items, overpowered, magic, creation, laboratory, isekai, adventure, fantasy.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "Cheat Magician", 
    file: "CheatMagician.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BNGU1YzdiY2QtOThkZi00YmU4LWFkNGItMGE3MDEwNWNmN2U0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Cheat Magician Poster",
    genre: "Fantasy • Action", 
    episodes: "▶️ 12",
    studio: "Encourage Films",
    rating: "⭐ 3", 
    description: "Taichi and Rin are normal high school students who are suddenly summoned to the world of Altia. While testing their mana levels, they discover they possess magic power far beyond anyone else in the world, allowing them to use 'cheat' spells that bypass the laws of nature.",
    hook: "Two friends are summoned to a fantasy world with magical power that is literally a 'cheat' code.",
    quote: "We're cheats. This level of power shouldn't even be possible in this world.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Action, Fantasy, Shonen, Overpowered, Magic System, Adventure, Battle, Supernatural, Quest, Friendship, Survival, Kingdom Fantasy, Summoning, Journey, Leveling, Elements",
    keywords: "Cheat-powers, isekai, magic, stats, overpowered, friends, fantasy, action, summoning.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "Assassin Pride", 
    file: "AssassinsPride.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BMzkwMmE2YjMtNDY5MC00ZDFjLWFhNWEtNjMwN2RmNGIyZGRhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Assassin Pride Poster",
    genre: "Fantasy • Mystery", 
    episodes: "▶️ 12",
    studio: "EMT Squared",
    rating: "⭐ 4", 
    description: "In a world where only nobles possess mana to fight monsters, Melida is a noble girl who has yet to manifest any power. Kufa is an assassin sent to be her tutor, with secret orders to kill her if she is found to be talentless. Moved by her pride, he chooses to help her fake her magic.",
    hook: "An assassin sent to execute a talentless noble girl chooses to train her in secret instead.",
    quote: "I'll protect your pride. Even if the world says you have no mana, I'll show them your worth.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Fantasy, Mystery, Seinen, Action, Supernatural, Assassin, School Life, Magic System, Noble Society, High Society, Gothic, Dark Fantasy, Romance, Drama, Secret Identity, Martial Arts, Tutorship",
    keywords: "Assassin, student, noble, mana, bloodline, teaching, secrets, hidden-power, gothic, fantasy.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "Seirei Gensouki", 
    file: "Seirei.html", 
    poster: "https://m.media-amazon.com/images/I/71Va6PGC+RL._AC_UF894,1000_QL80_.jpg", 
    alt: "Seirei Gensouki Poster",
    genre: "Adventure • Fantasy", 
    episodes: "▶️ 24",
    studio: "TMS Entertainment",
    rating: "⭐ 4", 
    description: "Rio is a street orphan living in a fantasy world's slums. After waking up with the memories of a Japanese student, he discovers he has vast hidden magical potential. After saving a kidnapped princess, he is enrolled in a royal academy, but his past soon catches up with him.",
    hook: "An orphan slum-dweller awakens past-life memories and incredible magic to change his fate.",
    quote: "I remember everything. My past life and this one... I'll find my own path in this world.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Fantasy, Adventure, Action, Shonen, Reincarnation, Overpowered, Harem, Magic System, Revenge, Drama, Noble Society, High Society, Journey, Past Life, Spirits, Martial Arts, Survival",
    keywords: "Memories, reincarnation, orphan, noble, magic, spirits, journey, revenge, betrayal, past-life.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "No Longer Allowed In Another World", 
    file: "Nihilist.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BYjEwNWYzYmUtZTlmYi00OTA3LTljOTEtYTVmZjNiNTQyYTAxXkEyXkFqcGc@._V1_.jpg", 
    alt: "No Longer Allowed Poster",
    genre: "Comedy • Dark Fantasy", 
    episodes: "▶️ 12",
    studio: "Atelier Pontdarc",
    rating: "⭐ 5", 
    description: "Based on the life of Osamu Dazai, a famous depressed author is summoned to another world with his lover while attempting a double suicide. He finds the fantasy world's tropes irritating and uses his nihilistic wit to disrupt the typical hero-saves-the-world narrative.",
    hook: "A suicidal 20th-century author is summoned as a hero and finds the fantasy world incredibly annoying.",
    quote: "Is there a good place to die here? This world is too bright for someone like me.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Dark Comedy, Satire, Seinen, Psychological, Dark Fantasy, Philosophical, Literary, Parody, Adventure, Subversion, Nihilism, Life Lessons, Historical Figure, Surreal, Drama, Wit",
    keywords: "Author, suicidal, dark-humor, isekai, subversion, literary, satire, depressing, comedy.",
    trending: false,
    best: true,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "May I Ask for One Final Thing?",
    file: "OneFinalThing.html", 
    poster: "https://fwmedia.fandomwire.com/wp-content/uploads/2025/10/07125423/may-i-ask-for-one-final-thing-episode-2.jpg", 
    alt: "Final Thing Poster",
    genre: "Action • Romance", 
    episodes: "▶️ 12",
    studio: "Fanworks",
    rating: "⭐ 5", 
    description: "Scarlet is a refined noblewoman who has spent her life being polite despite being constantly mistreated. When her engagement is publicly annulled by a spoiled prince, she finally snaps and asks for one last thing: the permission to beat every person in the room into the ground.",
    hook: "A polite noblewoman finally snaps and asks to punch everyone in the room before her engagement ends.",
    quote: "May I punch every single one of you in the face?",
    watch: "https://aniwatchtv.to/watch/may-i-ask-for-one-final-thing-19927?ep=145501",
    trailer: "https://www.youtube.com/embed/4K4ZK_Nxigc?si=4WHq-n-6VZCCpyAg",
    laugh: "https://www.youtube.com/watch?v=l7J0q1GSR0M",
    spotify: "https://open.spotify.com/embed/playlist/6I7ukJPW0ZydnaS1hqcOQK?utm_source=generator",
    keyGenre: "Action, Romance, Shoujo, Drama, Fantasy, Noble Society, High Society, Retribution, Villainess, Martial Arts, Comedy, Justice, Satisfaction, Social Satire, Brawling, Historical Fantasy, Resilience",
    keywords: "Fist-fight, noble, engagement, broken, punch, action, lady, romance, dignity, strength.",
    trending: false,
    best: false,
    gold: false, silver: true, bronze: false
  },
  { 
    name: "My Status as an Assassin Obviously Exceeds the Hero's",
    file: "AssassinExceeds.html", 
    poster: "https://resizing.flixster.com/MpjKwK0ga7NTeDfOtXi-OmS1IMQ=/fit-in/352x330/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p30870171_b_h9_aa.jpg", 
    alt: "My Status as an Assassin Poster",
    genre: "Isekai • Action", 
    episodes: "▶️ 12",
    studio: "Studio Mother",
    rating: "⭐ 4", 
    description: "Akira and his classmates are summoned to a fantasy world as heroes. While his friends receive flashy 'Hero' classes, Akira becomes an 'Assassin.' He soon discovers that his stealth and lethality far exceed the 'Hero' class, forcing him to work from the shadows to uncover the kingdom's dark secrets.",
    hook: "A student is summoned as a 'weak' assassin, only to find he is more lethal than the party's Hero.",
    quote: "I'm the one in the shadows. The hero may have the light, but I have the truth.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Action, Fantasy, Shonen, Assassin, Overpowered, Revenge, Betrayal, Leveling, RPG Mechanics, Survival, Dark Fantasy, Strategy, Secret Identity, Adventure, Kingdom Intrigue, Tactical",
    keywords: "Protagonist, Invisible, Presence, Summoned, Kingdom, Conspiracy, Shadows, Overpowered.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "No Game No Life", 
    file: "NGNL.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BMjRjMTA3ZDktZDBhMy00NjhjLTk1ODMtODU5NWE2NWExNzYxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "No Game No Life Poster",
    genre: "Game • Strategy", 
    episodes: "▶️ 12",
    studio: "Madhouse",
    rating: "⭐ 5", 
    description: "Sora and Shiro are genius gamer siblings who find the real world boring. They are challenged to a chess match by a god and summoned to Disboard, a world where violence is forbidden and every conflict is decided by games. They decide to challenge the God of Games himself.",
    hook: "Two hikikomori geniuses are summoned to a world where everything is decided by high-stakes games.",
    quote: "Blank never loses. In a world ruled by games, we are the absolute masters.",
    watch: "https://aniwatchtv.to/watch/no-game-no-life-261?ep=5328",
    trailer: "https://www.youtube.com/embed/ETQUp-Omp-A?si=-iCE52Y0xIPmiOS_",
    laugh: "https://www.youtube.com/watch?v=8tg0SQJ4-Fg",
    spotify: "https://open.spotify.com/embed/playlist/5mNBbq9LGBPm9nYGoakZfj?utm_source=generator",
    keyGenre: "Isekai, Game, Strategy, Shonen, Comedy, Psychological, Overpowered, Mind Games, Logic, Ecchi, Adventure, Fantasy, Tactics, Supernatural, World Conquest, Colorful, Parody, Stakes, Siblings",
    keywords: "Games, logic, strategy, siblings, hikikomori, genius, fantasy, bets, rules, chess, cards.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: true
  },
  { 
    name: "The Rising Of The Shield Hero", 
    file: "ShieldHero.html", 
    poster: "https://m.media-amazon.com/images/I/81YJ8CeI7hL._AC_UF894,1000_QL80_.jpg", 
    alt: "Shield Hero Poster",
    genre: "Action • Adventure", 
    episodes: "▶️ 50",
    studio: "Kinema Citrus",
    rating: "⭐ 4", 
    description: "Naofumi Iwatani is summoned as the Shield Hero, the weakest of four legendary heroes. After being falsely accused of a crime and left with nothing, he becomes a bitter survivalist, slowly building his power through defensive ingenuity and the help of a demi-human slave he rescues.",
    hook: "Betrayed and hated by the world, a hero with only a shield must find a way to survive and fight.",
    quote: "I'll protect them my way. I don't need your recognition to save this world.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Action, Adventure, Seinen, Drama, Fantasy, Dark Fantasy, Betrayal, Redemption, Survival, Revenge, Strategy, RPG Mechanics, Leveling, Political Intrigue, Psychology, Resilience, Monster Hunter",
    keywords: "Shield, betrayal, resentment, isekai, defense, legendary-weapon, survival, growth, slaves.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "That Time I Got Reincarnated as a Slime", 
    file: "Slime.html", 
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9gVF8FG9Zno2pswhuCgcdVQ7gOiH9tBk56Q&s", 
    alt: "Slime Isekai Poster",
    genre: "Fantasy • Adventure", 
    episodes: "▶️ 72",
    studio: "Eight Bit",
    rating: "⭐ 3", 
    description: "Satoru Mikami is a lonely office worker who is killed and reborn as a humble Slime in a cave. Discovering he can devour anything and gain its skills, he accidentally becomes a powerhouse and eventually unites various monster tribes to build a peaceful nation of Jura Tempest.",
    hook: "A salaryman is reborn as a slime with the power to absorb any skill and builds a nation of monsters.",
    quote: "I'm not a bad slime. I just want to build a world where everyone can smile.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Fantasy, Adventure, Shonen, Overpowered, Nation Building, World Building, Magic System, Monster, Diplomacy, Politics, Evolution, Comedy, Action, Strategy, Civilization, Community, War",
    keywords: "Slime, nation-building, skills, monsters, absorption, evolution, isekai, fantasy, magic.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "Tsukimichi: Moonlit Fantasy", 
    file: "Tsukimichi.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BZGFjZDJkOWYtOTgwYy00MTI4LWJlNDItZWI1MWY4ZmY1ZDllXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Tsukimichi Poster",
    genre: "Action • Fantasy", 
    episodes: "▶️ 37",
    studio: "C2C / J.C.Staff",
    rating: "⭐ 5", 
    description: "Makoto Misumi is summoned to a fantasy world only for the goddess to reject him because she thinks he's 'too ugly.' She dumps him in a wasteland at the edge of the world, where he discovers his human body possesses god-like strength and he begins to lead a city of monsters.",
    hook: "Rejected by a goddess for his looks, a boy builds a thriving monster kingdom in a wasteland.",
    quote: "I'll make my own path. If the gods won't help me, I'll build my own world.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Action, Fantasy, Shonen, Overpowered, Comedy, World Building, Adventure, Magic System, Trade, Commerce, Mythology, Society, Parody, Supernatural, Harem, Monster, Survival",
    keywords: "Ugly-hero, banished, god-blessing, moon, monsters, isekai, trade, commerce, village.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "Black Summoner", 
    file: "BlackSummoner.html", 
    poster: "https://m.media-amazon.com/images/M/MV5BYmU2ZGFkY2MtYTVlOS00ZmExLThjMzMtY2MwMWFiYTBmMDA3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Black Summoner Poster",
    genre: "Action • Fantasy", 
    episodes: "▶️ 12",
    studio: "Satelight",
    rating: "⭐ 5", 
    description: "Kelvin woke up in a new world with no memories of his past life, having traded them away for god-level summoning skills. He is a 'battle junkie' who grows more powerful by contracting with powerful monsters and heroes, all while hiding his identity as an S-rank adventurer.",
    hook: "A battle-junkie trades his memories for god-level summoning skills to fight the world's strongest.",
    quote: "I live for the thrill of the fight. Every contract I make is a step toward a stronger enemy.",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Isekai, Action, Fantasy, Shonen, Overpowered, Magic System, Battle Junkie, RPG Mechanics, Leveling, Harem, Summoning, Adventure, Monsters, Combat, Strategy, Supernatural, Thriller",
    keywords: "Summoner, memories, trade, overpowered, battle-junkie, isekai, magic, skills, contracts.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  },
  { 
    name: "The Devil Is A Part-Timer!", 
    file: "DevilPartTimer.html", 
    poster: "https://m.media-amazon.com/images/S/pv-target-images/1ece32964be68fdaa1bdd12c4f41e55f3a68ff6b66860be05af47d4b53449efb._SX1080_FMjpg_.jpg", 
    alt: "Devil Is A Part-Timer Poster",
    genre: "Comedy • Fantasy", 
    episodes: "▶️ 37",
    studio: "White Fox / Studio 3Hz",
    rating: "⭐ 4", 
    description: "Demon Lord Satan is on the verge of conquering the world of Ente Isla until a Hero drives him away. He escapes through a portal to modern-day Tokyo, where magic is rare. Stripped of his powers, he takes a job flipping burgers at 'MgRonald’s' to pay rent and plot his return.",
    hook: "The Demon Lord is forced to escape to modern Tokyo and take a part-time job at a fast-food joint.",
    quote: "I will conquer this world... starting with the regional manager position!",
    watch: "",
    trailer: "",
    laugh: "",
    spotify: "",
    keyGenre: "Reverse Isekai, Comedy, Fantasy, Slice of Life, Shonen, Workplace Drama, Supernatural, Urban Fantasy, Satire, Daily Life, Modern, Parody, Humor, Demon Lord, Action, Romance, Social Satire",
    keywords: "Satan, fast-food, reverse-isekai, comedy, burger, hero, magic, modern-world, poverty, survival.",
    trending: false,
    best: false,
    gold: false, silver: false, bronze: false
  }
];